

classDiagram



    InventarioService ..|> InventarioServiceImp : Implementa
    InventarioController -- InventarioService
    InventarioServiceImp -- Usuario_Gestor

    AgendaService ..|> AgendaServiceImp : Implementa
    AgendaController -- AgendaService
    AgendaServiceImp -- Agenda
    
    Usuario_Gestor -- Inventario
    Inventario -- ElementoInventario
    Usuario_Gestor -- Agenda
    Agenda -- Renta


    class InventarioService{
      <<Interfaz>>
      + crearNuevoElemento(nuevoElemento : Elemento) void
      + eliminarElemento(elementoEliminado : Elemento) void
      + cambiarEstadoDeElemento(elementoCambiado : Elemento) void
      + ReducirAlmacenDeElemento(elementoReducido : Elemento) void
      + AumentarAlmacenDeElemento(elementoAumentado : Elemento) void
    }

    class AgendaService{
      <<Interfaz>>
      + ObtenerRentas() void
      + AgregarRenta() void
      + EliminarRenta() void
    }

    class InventarioServiceImp{
      
    }

     class AgendaServiceImp{
      
    }


    class InventarioController{

    }

    class AgendaController{

    }

    class ElementoInventario{
      - m_nombre : String
      - m_categoria : enum
      - m_cantidad : int
      
      + ReducirAlmacen(reduccion : int) void
      + AumentarAlmacen( aumento : int) void
    }

    class Inventario{
      - m_elementos : ArrayList Elemento
      + AgregarElemento(nuevoElemento : Elemento) : void
      + EliminarElemento(elementoEliminado : Elemento) : void
      + ObtenerElemento(index : int) : Elemento
    }

    class Renta{
      - m_direccion : Direccion
      - m_elementosRentados : ArrayList Elemento
      - m_contacto : String
      - m_fecha : Date
    }

    class Agenda{
      - m_rentas : ArrayList Renta
      + AgregarRecordatorio(rentaNueva : Renta) void
      + EliminarRecordatorio(rentaEliminada : Renta) void
    }

    class Usuario_Gestor{
      + crearRenta() void
      + eliminarRenta() void
      + AgregarElemento() void
      + EliminarElemento() void
    }